name: Bug report 🐛
description: Report a reproducible bug or regression in this library.
labels: [bug]
body:
    - type: markdown
      attributes:
          value: |
              # Bug report

              👋 Hi! Thank you so much for taking the time to submit a bug report — it really helps us improve the library. We appreciate it! 🙏

              **Please fill out the following carefully before opening a new issue ❗**
              *(Your issue may be closed if it doesn't provide the required pieces of information)*

    - type: checkboxes
      attributes:
          label: Before submitting a new issue
          description: Please perform simple checks first.
          options:
              - label: I tested using the latest version of the library, as the bug might be already fixed.
                required: true
              - label: I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
                required: true
              - label: I checked for possible duplicate issues, with possible answers.
                required: true

    - type: checkboxes
      attributes:
          label: Affected platforms
          description: Please select all platforms where the bug occurs.
          options:
              - label: iOS
              - label: Android
              - label: Web

    - type: textarea
      id: summary
      attributes:
          label: Bug summary
          description: Provide a clear and concise description of what the bug is. Include error messages, stack traces, screenshots, etc.
      validations:
          required: true

    - type: input
      id: library-version
      attributes:
          label: Library version
          description: What version of the library are you using?
          placeholder: 'x.x.x'
      validations:
          required: true

    - type: textarea
      id: react-native-info
      attributes:
          label: Environment info
          description: Run `npx react-native info` in your terminal and paste the results below.
          value: |
              ```
              # Paste output of `npx react-native info` here inside this code block
              ```
      validations:
          required: true

    - type: textarea
      id: steps-to-reproduce
      attributes:
          label: Steps to reproduce
          description: Provide a clear list of steps and code to reproduce the problem.
          value: |
              1. …
              2. …
      validations:
          required: true

    - type: checkboxes
      attributes:
          label: Can be reproduced in the example app?
          description: Please confirm whether this issue can be reproduced in the provided example app.
          options:
              - label: Yes, I can reproduce this in the example app.

    - type: input
      id: reproducible-example
      attributes:
          label: Reproducible example repository
          description: Link to a GitHub repo that demonstrates the bug clearly.
          placeholder: https://github.com/your-username/your-example
      validations:
          required: true
